apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: intellipaat-cluster
  region: us-west-2

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 3
    ssh: 
      allow: true
      publicKeyName: eks-course
